version: '3'
services:
  db:
    image: mysql:5.7.19
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    command: bundle exec rails s -p 3006 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3006:3006"
    # depends_on:
    #   - db
    links:
    - db
